name: Build on MacOS

on:
    workflow_call:
        inputs:
            tag-name:
                type: string
                required: true
        outputs:
            runid:
                value: ${{github.run_id}}
    workflow_dispatch:
        inputs:
            tag-name:
                type: string
                required: true

jobs:
    build:
        runs-on: macos-latest
        steps:

          - name: Checkout This Repo
            uses: actions/checkout@v4
            with:
                ref: main

          - name: Checkout SoLoud Source Code
            shell: bash
            run: |
                curl -LO "https://github.com/jarikomppa/soloud/archive/refs/tags/${{inputs.tag-name}}.zip"
                unzip ${{inputs.tag-name}}.zip

          - name: Download GENie
            shell: bash
            run: |
                cd soloud-${{inputs.tag-name}}/build
                curl -LO "https://github.com/bkaradzic/bx/raw/master/tools/bin/darwin/genie"
                chmod +x genie

          - name: Build MacOS arm64
            shell: bash
            run: |
                cd soloud-${{inputs.tag-name}}/build
                ./genie --with-coreaudio xcode15
                cd xcode15
                xcodebuild -project SoloudStatic.xcodeproj -scheme SoloudStatic -configuration Debug ARCHS=arm64 -derivedDataPath arm64.debug clean build
                ls
                fedwsgd
                xcodebuild -project SoloudStatic.xcodeproj -scheme SoloudStatic -configuration Release ARCHS=arm64 clean build
                mv ../../lib/libsoloud_static.a ../../lib/libsoloud_static_arm64.a

          - name: Build MacOS x64
            shell: bash
            run: |
                cd soloud-${{inputs.tag-name}}/build
                rm -rf ninja
                ./genie --with-coreaudio --platform=x64 ninja
                arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                arch -x86_64 env \
                    HOMEBREW_BUILD_FROM_SOURCE=1 \
                    CFLAGS="-arch x86_64" \
                    CXXFLAGS="-arch x86_64" \
                    /usr/local/bin/brew install ninja
                arch -x86_64 ninja -C debug64 SoloudStatic
                arch -x86_64 ninja -C release64 SoloudStatic
                cd ../../lib
                ls

          - name: Compress Product
            shell: bash
            run: |
                echo ${{inputs.tag-name}} >> VERSION.txt
                mkdir -p temp/include/soloud
                cp -a soloud-${{inputs.tag-name}}/include/* temp/include/soloud
                7z a soloud_macos_arm64_debug.7z ./soloud-${{inputs.tag-name}}/lib/libsoloud_static_x64_d.a ./temp/include VERSION.txt
                7z a soloud_macos_arm64_release.7z ./soloud-${{inputs.tag-name}}/lib/libsoloud_static_x64.a ./temp/include VERSION.txt

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: soloud_macos_arm64
                path: |
                    *.7z
                retention-days: 7