name: Build on MacOS

on:
    workflow_call:
        inputs:
            commit:
                type: string
                required: true
        outputs:
            runid:
                value: ${{github.run_id}}
    workflow_dispatch:
        inputs:
            commit:
                type: string
                description: Target commit
                required: true

jobs:
    build:
        runs-on: macos-latest
        steps:

          - name: Checkout SoLoud
            uses: actions/checkout@v4
            with:
                repository: jarikomppa/soloud
                path: soloud

          - name: Download GENie and Generate Build Files
            shell: bash
            run: |
                cd soloud/build
                curl -LO "https://github.com/bkaradzic/bx/raw/master/tools/bin/darwin/genie"
                chmod +x genie
                ./genie --with-coreaudio xcode15

          - name: Build MacOS x64
            shell: bash
            run: |
                cd soloud/build/xcode15
                xcodebuild -project SoloudStatic.xcodeproj -scheme SoloudStatic -configuration Debug ARCHS=x86_64 clean build
                mv ../../lib/libsoloud_static.a ../../libsoloud_static_x64_d.a
                xcodebuild -project SoloudStatic.xcodeproj -scheme SoloudStatic -configuration Release ARCHS=x86_64 clean build
                mv ../../lib/libsoloud_static.a ../../libsoloud_static_x64.a

          - name: Build MacOS arm64
            shell: bash
            run: |
                cd soloud/build/xcode15
                xcodebuild -project SoloudStatic.xcodeproj -scheme SoloudStatic -configuration Debug ARCHS=arm64 clean build
                mv ../../lib/libsoloud_static.a ../../libsoloud_static_arm64_d.a
                xcodebuild -project SoloudStatic.xcodeproj -scheme SoloudStatic -configuration Release ARCHS=arm64 clean build
                mv ../../lib/libsoloud_static.a ../../libsoloud_static_arm64.a

          - name: Compress Product
            shell: bash
            run: |
                echo ${{inputs.commit}} >> VERSION.txt
                mkdir -p temp/include/soloud
                cp -a soloud/include/* temp/include/soloud
                7z a soloud_macos_x64_debug.7z ./soloud/libsoloud_static_x64_d.a ./temp/include VERSION.txt
                7z a soloud_macos_x64_release.7z ./soloud/libsoloud_static_x64.a ./temp/include VERSION.txt
                7z a soloud_macos_arm64_debug.7z ./soloud/libsoloud_static_arm64_d.a ./temp/include VERSION.txt
                7z a soloud_macos_arm64_release.7z ./soloud/libsoloud_static_arm64.a ./temp/include VERSION.txt

          - name: Upload Archive x64
            uses: actions/upload-artifact@v4
            with:
                name: soloud_macos
                path: |
                    *.7z
                retention-days: 7